export * from "./AboutPage/AboutPage"
export * from "./CommentPage/CommentPage"
export * from "./HomePage/HomePage"
export * from "./PostPage/PostPage"
export * from "./UserPage/UserPage"
export * from "./NotFoundPage/NotFoundPage"
export * from "./SinglePostPage/SinglePostPage"
export * from "./LoginPage/LoginPage"
